"""
pyxie game engine
"""

try:
    from pyxie._pyxie import *
except ModuleNotFoundError:
    from _pyxie import *

SAMPLERSTATE_WRAP = 0
SAMPLERSTATE_MIRROR = 1
SAMPLERSTATE_CLAMP = 2
SAMPLERSTATE_BORDER = 3
SAMPLERSTATE_LINEAR = 0
SAMPLERSTATE_NEAREST = 1
SAMPLERSTATE_NEAREST_MIPMAP_NEAREST = 2
SAMPLERSTATE_LINEAR_MIPMAP_NEAREST = 3
SAMPLERSTATE_NEAREST_MIPMAP_LINEAR = 4
SAMPLERSTATE_LINEAR_MIPMAP_LINEAR = 5

TARGET_PLATFORM_PC = 0
TARGET_PLATFORM_IOS = 1
TARGET_PLATFORM_ANDROID = 2

ANIMETION_PART_A = 0
ANIMETION_PART_B = 1
ANIMETION_PART_C = 2

ANIMETION_SLOT_A0 = 1
ANIMETION_SLOT_A1 = 2
ANIMETION_PART_B0 = 3
ANIMETION_PART_B1 = 4
ANIMETION_PART_C0 = 5
ANIMETION_PART_C1 = 6
